seed-1:
  image: xview-cluster
  entrypoint: /opt/docker/bin/xview_cluster_seed_boot
  hostname: seed-1
  ports:
    - 2551
  environment:
    CLUSTER_HOST: seed-1
    CLUSTER_SEEDS: seed-1
    CLUSTER_ROLE: seed

seed-2:
  image: xview-cluster
  entrypoint: /opt/docker/bin/xview_cluster_seed_boot
  hostname: seed-2
  ports:
    - 2551
  links:
    - seed-1
  environment:
    CLUSTER_HOST: seed-2
    CLUSTER_SEEDS: seed-1
    CLUSTER_ROLE: seed

frontend:
  image: xview-cluster
  entrypoint: /opt/docker/bin/xview_cluster_frontend_boot
  hostname: frontend
  ports:
    - 9000:9000
    - 2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0
    CLUSTER_ROLE: frontend

master:
  image: xview-cluster
  entrypoint: /opt/docker/bin/xview_cluster_master_boot
  hostname: master
  ports:
    - 2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0
    CLUSTER_ROLE: master

worker:
  image: xview-cluster
  entrypoint: /opt/docker/bin/xview_cluster_worker_boot
  hostname: master
  volumes:
    - /usr/local/data:/data:ro
  ports:
    - 2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0
    CLUSTER_ROLE: worker
    AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
    SOURCE_PATH: ${S3_SOURCE_PATH}
