seed-1:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_seed_boot
  hostname: seed-1
  ports:
    - 2551:2551
  environment:
    CLUSTER_HOST: seed-1
    CLUSTER_SEEDS: seed-1

seed-2:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_seed_boot
  hostname: seed-2
  ports:
    - 2552:2551
  links:
    - seed-1
  environment:
    CLUSTER_HOST: seed-2
    CLUSTER_SEEDS: seed-1

worker-1:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_node_boot
  hostname: worker-1
  ports:
    - 2553:2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0

worker-2:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_node_boot
  hostname: worker-2
  ports:
    - 2554:2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0

worker-3:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_node_boot
  hostname: worker-3
  ports:
    - 2555:2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0

frontend:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_frontend_boot
  hostname: frontend
  ports:
    - 2550:2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0
