seed-1:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_seed_boot
  hostname: seed-1
  ports:
    - 2551
  environment:
    CLUSTER_HOST: seed-1
    CLUSTER_SEEDS: seed-1
    CLUSTER_ROLE: seed

seed-2:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_seed_boot
  hostname: seed-2
  ports:
    - 2551
  links:
    - seed-1
  environment:
    CLUSTER_HOST: seed-2
    CLUSTER_SEEDS: seed-1
    CLUSTER_ROLE: seed

frontend:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_frontend_boot
  hostname: frontend
  ports:
    - 9000:9000
    - 2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0
    CLUSTER_ROLE: frontend

master:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_master_boot
  hostname: worker-1
  ports:
    - 2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0
    CLUSTER_ROLE: master

worker:
  image: cluster
  entrypoint: /opt/docker/bin/xview_cluster_worker_boot
  hostname: worker-1
  volumes:
    - /usr/local/data:/data:ro
  ports:
    - 2551
  links:
    - seed-1
    - seed-2
  environment:
    CLUSTER_SEEDS: seed-1,seed-2
    CLUSTER_HOST: ""
    CLUSTER_PORT: 0
    CLUSTER_ROLE: worker
    S3_URI: http://172.16.105.83:3000
