apiVersion: v1
kind: Template
metadata:
  name: xview-cluster-frontend

parameters:
  - name: NAME
    displayName: Cluster Name
    value: chipper
    required: true

  - name: DOCKER_IMAGE
    displayName: Docker image
    value: jwiii/xview-cluster
    required: true

  - name: DOCKER_TAG
    displayName: Docker Tag
    value: latest
    required: true

  - name: REST_API_DOMAIN
    displayName: REST API Domain
    value: openshift.com
    required: true

objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-frontend
      name: ${NAME}-frontend
    spec:
      ports:
        - name: 9000-tcp
          port: 9000
          protocol: TCP
          targetPort: 9000
      selector:
        app: ${NAME}-frontend
        deploymentconfig: ${NAME}-frontend
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}

  - apiVersion: v1
    kind: Route
    metadata:
      name: ${NAME}-frontend
    spec:
      host: ${NAME}-cluster.${REST_API_DOMAIN}
      to:
        kind: Service
        name: ${NAME}-frontend
        weight: 100
      port:
        targetPort: 9000-tcp
      wildcardPolicy: None

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      generation: 1
      labels:
        app: ${NAME}-frontend
      name: ${NAME}-frontend
    spec:
      replicas: 1
      selector:
        app: ${NAME}-frontend
        deploymentconfig: ${NAME}-frontend
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${NAME}-frontend
            deploymentconfig: ${NAME}-frontend
        spec:
          containers:
            - name: ${NAME}-frontend
              image: ${DOCKER_IMAGE}:${DOCKER_TAG}
              env:
                - name: CLUSTER_SEEDS
                  value: ${NAME}-seed-0.akka-seed,${NAME}-seed-1.akka-seed
                - name: CLUSTER_HOST
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
              command: ["/bin/sh", "-c", "/opt/docker/bin/xview_cluster_frontend_boot"]
              livenessProbe:
                tcpSocket:
                  port: 2551
              ports:
                - containerPort: 2551
                  protocol: TCP
              imagePullPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}:latest
          type: ImageChange
