apiVersion: v1
kind: Template
metadata:
  name: xview-cluster-master

parameters:
  - name: NAME
    displayName: Cluster Name
    value: chipper
    required: true

  - name: DOCKER_IMAGE
    displayName: Docker image
    value: jwiii/xview-cluster
    required: true

  - name: DOCKER_TAG
    displayName: Docker Tag
    value: latest
    required: true

objects:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        run: ${NAME}
      name: ${NAME}-master
    spec:
      replicas: 1
      selector:
        matchLabels:
          run: ${NAME}-master
      template:
        metadata:
          labels:
            run: ${NAME}-master
        spec:
          containers:
            - name: ${NAME}-master
              image: ${DOCKER_IMAGE}:${DOCKER_TAG}
              env:
                - name: CLUSTER_SEEDS
                  value: ${NAME}-seed-0.akka-seed,${NAME}-seed-1.akka-seed
                - name: CLUSTER_HOST
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
              command: ["/bin/sh", "-c", "/opt/docker/bin/xview_cluster_master_boot"]
              livenessProbe:
                tcpSocket:
                  port: 2551
              ports:
                - containerPort: 2551
                  protocol: TCP
              imagePullPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}:latest
          type: ImageChange
