apiVersion: v1
kind: Template
metadata:
  name: xview-cluster-worker

parameters:
  - name: NAME
    displayName: Cluster Name
    value: chipper
    required: true

  - name: DOCKER_TAG
    displayName: Version
    value: latest
    required: true

  - name: REPLICAS
    displayName: Number of worker nodes
    value: '3'
    required: true

objects:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: ${NAME}-worker
      labels:
        run: ${NAME}
    spec:
      replicas: ${REPLICAS}
      selector:
        matchLabels:
          run: ${NAME}-worker
      template:
        metadata:
          labels:
            run: ${NAME}-worker
          annotations:
            alpha.image.policy.openshift.io/resolve-names: '*'
        spec:
          containers:
            - name: ${NAME}-worker
              image: ${NAME}:latest
              env:
                - name: CLUSTER_ROLE
                  value: worker
                - name: CLUSTER_SEEDS
                  value: ${NAME}-seed-0.${NAME}-seed,${NAME}-seed-1.${NAME}-seed
                - name: CLUSTER_HOST
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
              command: ["/bin/sh", "-c", "/opt/app-root/src/cluster/target/universal/stage/bin/xview_cluster_worker_boot"]
              livenessProbe:
                tcpSocket:
                  port: 2551
              ports:
                - containerPort: 2551
                  protocol: TCP
              imagePullPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-worker
            from:
              kind: ImageStreamTag
              name: ${NAME}:latest

