kind: Template
apiVersion: v1
metadata:
  name: xview-cluster-frontend
labels:
  app: ${NAME}
  template: xview-cluster
  xview/cluster.role: frontend

parameters:
  - name: NAME
    displayName: Cluster Name
    value: chipper
    required: true

  - name: DOCKER_TAG
    displayName: Version
    value: latest
    required: true

  - name: REST_API_DOMAIN
    displayName: REST API Domain
    value: openshift.com
    required: true

objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}-frontend
      labels:
        app: ${NAME}-frontend
    spec:
      ports:
        - name: 9000-tcp
          port: 9000
          protocol: TCP
          targetPort: 9000
      selector:
        app: ${NAME}-frontend
        deploymentconfig: ${NAME}-frontend
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}

  - apiVersion: v1
    kind: Route
    metadata:
      name: ${NAME}-frontend
    spec:
      host: ${NAME}-cluster.${REST_API_DOMAIN}
      to:
        kind: Service
        name: ${NAME}-frontend
        weight: 100
      port:
        targetPort: 9000-tcp
      wildcardPolicy: None

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}-frontend
      labels:
        app: ${NAME}-frontend
    spec:
      replicas: 1
      selector:
        app: ${NAME}-frontend
        deploymentconfig: ${NAME}-frontend
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            alpha.image.policy.openshift.io/resolve-names: '*'
          labels:
            app: ${NAME}-frontend
            deploymentconfig: ${NAME}-frontend
        spec:
          containers:
            - name: ${NAME}-frontend
              image: ${NAME}:latest
              env:
                - name: CLUSTER_ROLE
                  value: frontend
                - name: CLUSTER_SEEDS
                  value: ${NAME}-seed-0.${NAME}-seed,${NAME}-seed-1.${NAME}-seed
                - name: CLUSTER_HOST
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
              command: ["/bin/sh", "-c", "/opt/app-root/src/cluster/target/universal/stage/bin/xview_cluster_frontend_boot"]
              livenessProbe:
                tcpSocket:
                  port: 2551
              ports:
                - containerPort: 2551
                  protocol: TCP
              imagePullPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
            - ${NAME}-frontend
            from:
              kind: ImageStreamTag
              name: ${NAME}:latest
