kind: Template
apiVersion: v1
metadata:
  name: xview-cluster-master
labels:
  app: ${NAME}
  template: xview-cluster
  xview/cluster.role: master

parameters:
  - name: NAME
    displayName: Cluster Name
    value: chipper
    required: true

  - name: DOCKER_TAG
    displayName: Version
    value: latest
    required: true

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}-master
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}-master
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            alpha.image.policy.openshift.io/resolve-names: '*'
          labels:
            run: ${NAME}-master
            deploymentconfig: ${NAME}-master
        spec:
          containers:
            - name: ${NAME}-master
              image: ${NAME}:latest
              env:
                - name: CLUSTER_ROLE
                  value: master
                - name: CLUSTER_SEEDS
                  value: ${NAME}-seed-0.${NAME}-seed,${NAME}-seed-1.${NAME}-seed
                - name: CLUSTER_HOST
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
              command: ["/bin/sh", "-c", "/opt/app-root/src/cluster/target/universal/stage/bin/xview_cluster_master_boot"]
              livenessProbe:
                tcpSocket:
                  port: 2551
              ports:
                - containerPort: 2551
                  protocol: TCP
              imagePullPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-master
            from:
              kind: ImageStreamTag
              name: ${NAME}:latest

