apiVersion: v1
kind: Template
metadata:
  name: xview-cluster-seed

parameters:
  - name: NAME
    displayName: Cluster Name
    value: chipper
    required: true

  - name: DOCKER_TAG
    displayName: Version
    value: latest
    required: true

objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        run: ${NAME}
      name: ${NAME}-seed
    spec:
      ports:
        - port: 2551
          protocol: TCP
          targetPort: 2551
      selector:
        run: ${NAME}-seed
      clusterIP: None

  - apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: ${NAME}-seed
      labels:
        run: ${NAME}-seed
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
    spec:
      serviceName: ${NAME}-seed
      replicas: 2
      selector:
        matchLabels:
          run: ${NAME}-seed
      template:
        metadata:
          labels:
            run: ${NAME}-seed
        spec:
          containers:
            - name: ${NAME}-seed
              image: ${NAME}:latest
              env:
                - name: CLUSTER_ROLE
                  value: seed
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: CLUSTER_SEEDS
                  value: ${NAME}-seed-0.${NAME}-seed
              command: ["/bin/sh", "-c", "CLUSTER_HOST=${POD_NAME}.${NAME}-seed /opt/app-root/src/cluster/target/universal/stage/bin/xview_cluster_seed_boot"]
              livenessProbe:
                tcpSocket:
                  port: 2551
              ports:
                - containerPort: 2551
                  protocol: TCP
              imagePullPolicy: Always
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-seed
            from:
              kind: ImageStreamTag
              name: ${NAME}:latest
